### ISSUE TITLE
Compatibility issue

### ISSUE THREAD

**Issue by UptightCarp03** [Ferret-Master/Commander-Merger#3]
So I don't know if its something I'm doing wrong, but when I downloaded the mod I was still having compatibility issues with the legion, new wave, and bug mods. Is there any way to fix the mod so I can run them all together?

**Comment by Ferret-Master** [comment]
with bugs being published and relying on this it should be auto enabled, bugs, second wave, and legion should work fine together and I have played and hosted games with that setup

make sure the merge box is ticked in the top left of community mods, if you have any other mods that add commanders they could cause an issue


just in case, this mod is purely so the lobby/commander selection works at all/properly with multiple factions. are your compatibility issues at the lobby stage or the in game stage, which would imply a different issue
